@baseURL = http://127.0.0.1:8000
@resource = natural-person

###
# @name all
GET {{baseURL}}/api/{{resource}}

###
# @name create
POST {{baseURL}}/api/{{resource}}
Content-Type: application/json

{
    "name": "Rodrigo Matias",
    "city_id": 3
}

###
# @name getOne
GET {{baseURL}}/api/{{resource}}/1


###
# @name update
PUT {{baseURL}}/api/{{resource}}/1
Content-Type: application/json

{
    "cpf": "12345678909"
}

###
# @name deleteOne
DELETE {{baseURL}}/api/{{resource}}/1